version: '3'

services:
  blockchain-app:
    build: .
    container_name: blockchain-app
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:delegated
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped 